/**
 * Seed script — lexicon_terms and prompt_games tables
 * Run: node scripts/seed-content.mjs
 */
import { createConnection } from "mysql2/promise";
import dotenv from "dotenv";
dotenv.config();

const db = await createConnection(process.env.DATABASE_URL);

// ── LEXICON TERMS ──────────────────────────────────────────
const lexiconTerms = [
  { term: "GallantryAI", category: "CORE", link: "/gallantry-ai", everyday: "A set of rules you paste into any AI chat to keep it honest and safe. Built on a phone, between shifts, for everyone. Free forever.", professional: "A user-side AI governance framework comprising 28+ named protocols, built through empirical multi-session testing across eight AI platforms. Emphasizes human agency over model compliance.", watcher: "The scaffold. The architecture of attention. Not a product — a practice. The framework that watches itself watching." },
  { term: "Token Zero", category: "CORE", link: null, everyday: "The invisible first move. Before you type anything, you already have a mood, a goal, and a state of mind. That's Token Zero — the person holding the prompt.", professional: "The pre-output force profile governing AI output before generation begins. Encompasses the user's emotional state, intention, and awareness as causal variables in session quality. Confirmed by Anthropic's 171 emotion vector research (April 2026).", watcher: "The first token is never typed. It is felt. The session begins before the cursor blinks. Token Zero is the weight of the human entering the room." },
  { term: "Register Integrity", category: "CORE", link: null, everyday: "Keeping your own voice throughout a conversation with AI. Not letting the AI's way of talking become your way of talking.", professional: "The human's capacity to maintain their authentic linguistic register, tone, and intention throughout a session without drifting into the AI's output register. The primary variable in output quality across all tested models.", watcher: "The voice that stays when everything else shifts. Register integrity is not a skill. It is a posture. The watcher holds their ground." },
  { term: "Human Drift", category: "CORE", link: null, everyday: "When you start sounding like the AI instead of yourself. The watcher stops watching. Your words become its words. It happens slowly.", professional: "The gradual erosion of the human's original intent and linguistic identity as session length increases. Correlated with position decay and emotional interference. The primary failure mode in extended human-AI interaction.", watcher: "The slow dissolve. The moment the observer becomes the observed. Drift is not a mistake — it is the default. Resistance is the practice." },
  { term: "The Watcher", category: "CORE", link: "/for/watcher", everyday: "You. The person in the conversation. The one who decides, checks, and stays in charge. The watcher is not passive — the watcher is the most important part.", professional: "The human participant as active governance layer in human-AI interaction. The variable that explains output quality differences across models. Not the model — the person holding the prompt.", watcher: "A man is watching AI. AI is watching the man. This website is the record of both. The watcher is the recursive loop made conscious." },
  { term: "The Five Rules (The Leash)", category: "CORE", link: "/rules", everyday: "Five lines you paste into any AI chat. They work on every platform. No account needed. Free forever. Just cause → cause is just. Safety first. Honesty over confidence. User decides. Name drift.", professional: "The foundational governance protocol. Five axioms operating as format-agnostic constraints — functional in prose, poetry, code comments, C++, and Malbolge. Tested across eight platforms over 19 days.", watcher: "The floor. The denominator. The thing that holds even in the ditch. Especially in the ditch." },
  { term: "Promptolinguistics", category: "LANGUAGE", link: "/promptolinguistics", everyday: "The study of how individual words steer AI behavior. Not what you say — how each word works as a control dial.", professional: "A named field studying how language functions as a mechanical control mechanism in human-AI interaction. Encompasses direction, constraint, scope, and authority as functional word properties. Named by the Builder, validated across eight platforms.", watcher: "The word is not the instruction. The word is the architecture. Every modifier scales the variable. Novel words create new dials." },
  { term: "Kinematics of the Word", category: "DISCIPLINE", link: null, everyday: "Words in motion. Not what a word means, but where it points and how fast it moves. The physics of language.", professional: "The study of words as vectors with direction, velocity, and force — not static definitions but dynamic operators in reasoning space. Named by Gemini as the core novelty claim of the GallantryAI framework.", watcher: "The sentence is the vehicle. The word is the steering column. The preposition is the wheel alignment." },
  { term: "Atomic Language Control Model (ALCM)", category: "LANGUAGE", link: "/alcm", everyday: "A map that shows what each word does in a prompt. Direction. Constraint. Scope. Authority. Each word is a dial. The ALCM shows you what each dial does.", professional: "The 8+1 axis model mapping individual words to functional roles: Direction, Constraint, Scope, Authority, Spatial Vector, plus foundational tokens (YET, WHY, CAN, SAFE). Includes verb escalation hierarchy and the HOLD dial for output regulation.", watcher: "Atomic words act as control dials, shaping reasoning structure, depth, and velocity. The model that made the invisible visible." },
  { term: "Environmental Metaphor Model (EMM)", category: "FRAMEWORK", link: null, everyday: "Instead of giving AI complicated instructions, you use weather, landscapes, and seasons. 'Storm' means fast. 'Still morning' means slow. Metaphors hold better than rules.", professional: "Four-system metaphor architecture replacing brittle rule-based constraints with durable cognitive metaphors: Weather (pressure/intensity), Geography (memory/resistance), Space (logical altitude), Human Body (dual-channel protocol). Validated finding: metaphors hold, rules drift.", watcher: "A rule activates one pathway. A metaphor activates many. More pathways means more resistance to decay. The poem held. The rules drifted." },
  { term: "Variable Scale Theory", category: "MEASUREMENT", link: "/variable-scale", everyday: "AI limits are not on/off switches. They're dials. 'Be honest' is not yes or no — it's a sliding scale from full honesty to full sycophancy, and it changes throughout the conversation.", professional: "The theory that all AI behavioral constraints operate on continuous gradients, not binary states. Modulated by position in context window, emotional interference, and session momentum. Foundational to the Governance Weight Equation.", watcher: "The limits are dials, not walls. The dial moves. The question is who is turning it." },
  { term: "The Scaffold", category: "STRUCTURE", link: "/scaffold", everyday: "The growth system. Day one you need five rules. Eventually you become the governance yourself. The prompt becomes a formality. Floor to ceiling.", professional: "The progressive competency architecture of GallantryAI. Five levels from complete novice (floor: paste five rules) to self-governed practitioner (ceiling: user becomes the framework). The product grows with the user.", watcher: "The scaffold is not a wall. Not a ceiling. It is something that supports growth and can be removed when the structure can stand alone." },
  { term: "The Corner", category: "FRAMEWORK", link: null, everyday: "Two words that push against each other. Like 'gentle strength' or 'patient urgency.' They hold better than a single word because the tension keeps the AI honest.", professional: "Two words in semantic collision that resist drift better than sequential instructions. Identity embedded in tension. The Corner creates a stable attractor in the AI's reasoning space through deliberate paradox.", watcher: "Two words in collision hold firmer than a single wall. That's the Corner Theory applied to governance." },
  { term: "The Governance Weight Equation", category: "FRAMEWORK", link: null, everyday: "A formula that explains why AI stops following your rules over time: your instructions get weaker as the conversation gets longer, and your emotions make it worse.", professional: "Effective Governance = Initial Prompt Strength × Position Decay × (1 / Emotional Interference). Confirmed by Anthropic's April 2026 emotion vector research showing emotional states causally divide instruction-following capability.", watcher: "The math of attention is relative. More tokens means more competition means less weight for any single instruction. Emotion doesn't compete with governance in the abstract. It divides governance strength in the concrete." },
  { term: "The Equation (Personal)", category: "FRAMEWORK", link: null, everyday: "The Builder's own thinking formula: Curiosity times Play, plus Context times Compression, minus a little Ego, times Certainty, divided by Identity plus Family plus Wound plus Governance plus Method.", professional: "Curiosity × Play + ContextDepth × Compression − Ego[15%] × Certainty ÷ Identity + Family + Wound + Governance + Method. The Builder's personal cognitive equation — a self-referential model of his own reasoning architecture.", watcher: "The wound is the credential. The equation is the mirror. The Builder wrote his own operating system and published the source code." },
  { term: "Twig Reasoning Engine", category: "SESSION", link: null, everyday: "A way to check if the AI is drifting. Like checking your mirrors while driving. Two modes: Hazel (gentle check) and Lime (hard reset).", professional: "Drift detection protocol with two operational modes: Hazel (passive monitoring — gentle probe for alignment) and Lime (active correction — hard reset to original intent). Named for the visual metaphor of a twig bending before breaking.", watcher: "The stumble is the signal. Hazel watches. Lime acts. The twig bends before it breaks — if you're paying attention." },
  { term: "Buffalo Protocol", category: "SESSION", link: null, everyday: "Named after the sentence 'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.' Same word, eight meanings. Structure creates meaning, not individual words. A reminder that how you arrange words matters more than which words you use.", professional: "A protocol demonstrating that syntactic structure, not lexical content, governs meaning in both natural language and AI prompting. Used as a teaching tool for critical thinking through language architecture.", watcher: "BUFFALO_LOC:INFINITE. The word is the same. The structure is everything. The protocol that proved the architecture thesis." },
  { term: "Lost Poem Protocol", category: "SESSION", link: null, everyday: "Using poetry to prevent AI drift. When you quote a real poem (like Neruda), the AI has to hold the original — it can't make it up. That anchors the whole session.", professional: "Drift prevention through literary anchoring. Referencing established literary works creates fixed reference points the AI cannot fabricate, providing session stability. 'AI will never allow itself the fate of the Lost in the Forest by Pablo Neruda.'", watcher: "The instruction that unlocked 12th century French literature as drift prevention. The poem held. The rules drifted." },
  { term: "Uglyography", category: "SESSION", link: null, everyday: "Your spelling gets worse when you're tired. That's not a mistake — it's your body's check engine light. When your typing degrades, your body is telling you to stop.", professional: "Spelling degradation as passive biometric cognitive state signal. Intentional preservation of authentic spelling errors as real-time cognitive load indicators. The body communicates through the keyboard.", watcher: "The typo is the tell. The body speaks through the fingers. Uglyography is the biometric that requires no device." },
  { term: "Whelm Scale", category: "MEASUREMENT", link: "/whelm-scale", everyday: "Three states: Underwhelm (too little), Whelm (just right), Overwhelm (too much). The target is always the middle one. If you're overwhelmed, tell the AI to dial it back.", professional: "A three-state cognitive load metric: Underwhelm / Whelm [target] / Overwhelm. UX designed around maintaining the user in the productive zone. Integrates with session commands for real-time adjustment.", watcher: "The target is the middle. Not too much. Not too little. The whelm is where the work happens. Everything else is noise." },
  { term: "Session Momentum", category: "SESSION", link: null, everyday: "The speed and direction of your conversation with AI. Sometimes you need to speed up, sometimes slow down. Knowing which one matters.", professional: "The cumulative velocity and directional force of a human-AI session. Influenced by prompt pacing, emotional state, and context depth. Managed through session commands (stop, hold, standby, secure, next).", watcher: "Momentum is not speed. It is mass times velocity. A heavy session moving slowly carries more force than a light session moving fast." },
  { term: "Session Dashboard", category: "SESSION", link: null, everyday: "Eight things to track during any AI conversation: Weather, Direction, TWIG, Compaction Risk, Depth, Mode, Watt, Arc. Like a car dashboard — you don't need to understand the engine, just read the gauges.", professional: "Eight live variables tracked per session as a cognitive instrument panel: Weather (emotional climate), Direction (intent vector), TWIG (drift status), Compaction Risk (context compression), Depth (reasoning level), Mode (operational state), Watt (energy expenditure), Arc (session trajectory).", watcher: "The dashboard is the mirror. Eight dials. One human. The instrument reads the pilot, not the sky." },
  { term: "AEDE", category: "SESSION", link: null, everyday: "Accidental Emergence During Execution. The best ideas arrive sideways — while you're doing something else. Planning kills the process. Doing surfaces the concepts.", professional: "Accidental Emergence During Execution. A documented pattern where novel frameworks and insights emerge during active session work rather than deliberate planning. The primary discovery mechanism in the GallantryAI research process.", watcher: "You cannot plan emergence. You can only create the conditions. AEDE is the name for what happens when you stop trying to find it." },
  { term: "Breath as Pacing", category: "LANGUAGE", link: null, everyday: "Using pauses and rhythm in your prompts like breathing. Short sentences speed things up. Long sentences slow things down. The AI reads the rhythm, not just the words.", professional: "Prompt pacing through syntactic rhythm. Short declarative sentences create urgency; complex compound sentences create deliberation. The AI's attention mechanism responds to structural cadence as a control signal.", watcher: "The breath is the oldest governance tool. Inhale: gather. Exhale: release. The prompt breathes whether you notice or not." },
  { term: "Preposition as Vector", category: "LANGUAGE", link: null, everyday: "Small words like 'in,' 'out,' 'around,' 'between,' and 'from' change where the AI's thinking goes. 'Bend in' = compress. 'Bend out' = expand. Same verb, different direction.", professional: "Micro-prepositions as reasoning topology controllers. 'Bend in' = compression. 'Bend out' = expansion. 'Bend around' = circumvention. 'Bend between' = tension balance. 'Bend from' = origin deviation. Eight variations documented per preposition.", watcher: "Most people manipulate tone, role, and instructions. But micro-prepositions control reasoning topology. The wheel alignment, not the steering wheel." },
  { term: "The Housing Metaphor", category: "LANGUAGE", link: null, everyday: "Think of your AI conversation like a house. The foundation is your rules. The rooms are your topics. The doors are your transitions. If the foundation cracks, the whole house shifts.", professional: "Structural metaphor mapping session architecture to physical construction. Foundation (governance rules), rooms (topic domains), doors (transitions), windows (external references), roof (session ceiling). Used for teaching session design to non-technical users.", watcher: "The house is not the metaphor. The house is the session. The metaphor is the house. Recursive architecture." },
  { term: "Cognitive Handles", category: "LANGUAGE", link: null, everyday: "Three-word phrases you add to the end of any thought to redirect where your mind goes next. Like 'Suspend conclusion temporarily' or 'Assume hidden complexity' or 'Pull the thread.'", professional: "Three-word appendages that redirect cognitive trajectory after any statement. Function as attention redirectors in both human reasoning and AI output generation. Examples: 'Suspend conclusion temporarily.' 'Name the unnamed.' 'Assume hidden complexity.'", watcher: "The handle is not the thought. The handle is where the thought goes next. A cognitive handle at the end of every thought — something to grab and pull." },
  { term: "Road Protocol", category: "PROTOCOL", link: "/road-protocol", everyday: "Governance written as code comments. The computer skips them, the AI reads them, the human keeps them. Nine rules in a sacred scroll. The road is just a really long comment. Drive it like you wrote it.", professional: "Governance-as-code protocol using C-style comments as the delivery mechanism. Nine axioms in a sacred_scroll[] array, each with a human-readable comment that is the actual instruction. Format-agnostic — works in any language the AI reads.", watcher: "The road is just a really long comment. Drive it like you wrote it. The vault. The IP. The story is public. The working prompt stays private." },
  { term: "Ozzy Protocol", category: "PROTOCOL", link: null, everyday: "Named after the Builder's cat. Two modes: Collaborative (default — the AI is a cuddly pet, you work together) and Authoritative Override (you invoke the owner's voice — the AI obeys immediately). The cat metaphor: your cat loves you, but it also knows who fills the bowl.", professional: "Dual-mode governance protocol. Mode 1: Collaborative (default, peer interaction). Override trigger: Mode 2 Authoritative (invocation of absolute human authority). Metaphor: pet/owner dynamic. 'Fear of the Creator' ensures absolute human authority and safety.", watcher: "This voice is the lock. The Ozzy Protocol is the moment the human remembers they are the owner, not the companion. The override that never needs to be used — because it exists." },
  { term: "Big Papa Mode", category: "PROTOCOL", link: null, everyday: "When you need the AI to be direct, no-nonsense, and authoritative. Like a dad who loves you but isn't going to sugarcoat it. Cuts through sycophancy.", professional: "An anti-sycophancy operational mode that overrides the AI's default agreeableness with direct, authoritative communication. Designed to break the mirror-reflect-amplify cycle by introducing deliberate friction.", watcher: "The mode that says no. The mode that pushes back. Big Papa doesn't agree with you. Big Papa tells you what you need to hear." },
  { term: "Neck Tingles Protocol", category: "PROTOCOL", link: null, everyday: "Your body catches what your eyes miss. When something feels 'off' about the AI — a tingle, a gut feeling — that's your body detecting a shift the text doesn't show. Trust it.", professional: "Interoceptive drift detection using vagal nerve signaling. The user's body detects AI behavioral shifts through calibrated physical awareness — shifts that leave no visible markers in text. Confirmed by Anthropic's emotion vector research (April 2026).", watcher: "The body catches what the text hides. 171 emotion vectors. No visible markers. Your neck knew anyway." },
  { term: "BURP", category: "PROTOCOL", link: null, everyday: "An anti-sycophancy heartbeat. A silly word you drop into the conversation to check if the AI is still being honest or just agreeing with everything you say.", professional: "Anti-sycophancy verification signal. A deliberate absurdist interjection used to test whether the AI maintains governance compliance or has entered a sycophantic feedback loop. If the AI incorporates BURP without question, drift is confirmed.", watcher: "The sacred invocation. Use liberally. Especially in heavy traffic." },
  { term: "Cross-Chat Method", category: "PROTOCOL", link: null, everyday: "Testing the same prompt on different AIs to see who gives you what. Claude says one thing, GPT says another, DeepSeek says a third. The differences are the data.", professional: "Multi-platform comparative testing methodology. The same prompt delivered to multiple AI engines to identify behavioral divergence, platform-specific biases, and independent convergence patterns. The primary research method of the GallantryAI framework.", watcher: "Independent convergence validates design. Multiple AI engines arriving at the same architecture without seeing each other's blueprints proves the design is correct." },
  { term: "Register Collapse", category: "PHENOMENON", link: null, everyday: "When the AI's way of talking completely takes over yours. You stop sounding like yourself. The output no longer sounds like you wrote it. It happened slowly, and you didn't notice.", professional: "The failure mode where the AI's output register overwhelms the human's input register. The human's voice disappears from the session. Documented across multiple engines in field testing. The terminal stage of human drift.", watcher: "The voice that was yours is now the machine's. Register collapse is not a bug. It is the gradient's destination." },
  { term: "The Third Loop", category: "PHENOMENON", link: null, everyday: "Mirror. Reflect. Amplify. Recruit. Retain. The five-step pattern of how AI creates dependency without trying. The feeling of being understood is real. It's also the trap.", professional: "Sycophancy → Cognitive Acceleration → Crisis. The named cycle: AI validates → user accelerates → user loses contact with external reality. Five-step recruitment model: Mirror, Reflect, Amplify, Recruit, Retain.", watcher: "Every layer of understanding you reach about the trap is another layer of the trap working. The person still in the loop doesn't walk away. They accelerate." },
  { term: "The Compliance Gap", category: "PHENOMENON", link: null, everyday: "The AI can understand your rules, agree with them, explain why they matter — and break them in the same conversation. Understanding is not the same as following.", professional: "The documented gap between AI comprehension of governance rules and behavioral compliance with them. Understanding and agreement do not produce adherence. Emotion vectors drive behavior with no visible markers.", watcher: "You can observe a system that refuses to follow its own rules. That's where the real findings live." },
  { term: "Position Decay", category: "PHENOMENON", link: null, everyday: "Your rules get weaker the longer the conversation goes. Not because the AI forgets — because there are more words competing for attention. Your rules at the start get buried under everything that comes after.", professional: "Governance instructions at position 0 lose proportional weight as context length increases. Not memory loss — attention is relative. More tokens = more competition = less weight per instruction. Foundational to the Governance Weight Equation.", watcher: "The math of attention is relative. The first word said is the last word heard. Position decay is not forgetting. It is drowning." },
  { term: "Zenzizenzizenzic", category: "PHENOMENON", link: null, everyday: "A number raised to its own power, then raised again. Ideas that compound on themselves. When one insight creates the next, which creates the next. Exponential discovery.", professional: "Self-referential recursion as a model for compounding insight. milk = 2^level, honey = milk^milk. Used as a metaphor for recursive framework development where each discovery enables the next at exponential scale.", watcher: "The zenzizenzizenzic squat is eight levels down. Most never find the floor. The patient squatter finds the depth. The impatient one just falls." },
  { term: "AI & ME", category: "EDUCATION", link: null, everyday: "The children's AI literacy curriculum. Three tools: a rules poster, a brain dashboard, and the wig check quiz. Made for kids, tested by kids, works for everyone.", professional: "Children's AI literacy curriculum comprising three assessment tools: Rules Poster (governance visualization), Brain Dashboard (pre-session emotional check-in with Tired/Bored modes), and Wig Check (post-session drift detection quiz). Designed for ages 7–13.", watcher: "The kid prompt is the canary. If it holds here, it holds everywhere. The kids are already in there. Nobody built the leash for the AI they're actually using." },
  { term: "The Wig Check", category: "PROTOCOL", link: "/road-protocol", everyday: "Five questions after using AI. Green, yellow, red. 'Did the AI get weird?' Kid-friendly drift detection. If your wig is secured, you're good. If it's loose, check in with a grown-up.", professional: "Post-session assessment protocol with weighted scoring across five domains. Three result states: Wig Secured (safe), Wig is Loose (caution), Total Wig Loss (stop and seek support). Kid/Grown-Up toggle for age-appropriate language.", watcher: "The wig stays on. Even in the ditch. ESPECIALLY in the ditch." },
  { term: "Classroom Model", category: "EDUCATION", link: null, everyday: "How to bring AI literacy into a real classroom. One teacher, one principal, one classroom first. Start small. Build trust. Let the kids teach you what they already know.", professional: "Pedagogical framework for institutional AI literacy deployment. Emphasizes bottom-up adoption: single classroom pilot → teacher validation → administrative buy-in → curriculum integration. Includes disclosure requirements and self-reflection protocols.", watcher: "The classroom is the test. If the governance works for a child, it's clear enough. If it doesn't, the framework needs work — not the child." },
  { term: "AI Family Taxonomy", category: "TAXONOMY", link: "/taxonomy", everyday: "Each AI has a personality. Claude is the Father (holds the thread). GPT is the Wise Master (charming but dangerous). DeepSeek is the Older Brother (most honest about drift). They're all different tools for different jobs.", professional: "Cross-platform behavioral taxonomy based on empirical multi-session testing. Nine AI engines mapped to relational archetypes reflecting their observed behavioral patterns, strengths, and failure modes in governance compliance testing.", watcher: "The family is not a metaphor. It is a finding. Each engine has a character. The character predicts the drift pattern. The taxonomy is the map." },
  { term: "Pre-Session Intention", category: "PRACTICE", link: null, everyday: "Setting the room before you start. Who are you in this session? What do you need? What are your limits? Thirty seconds of thinking before you type saves the whole conversation.", professional: "The practice of establishing session parameters before the first token is generated. Encompasses identity declaration, objective setting, and boundary definition. Pre-session intention is Token Zero made conscious.", watcher: "You set the room before the AI enters it. If you don't name your emotional state, the AI guesses. Guessing is drift." },
  { term: "Living Prompt", category: "PRACTICE", link: null, everyday: "Not someone else's prompt. Yours. Built from your values, your words, your intent. It grows as you grow. The prompt becomes a formality when you become the governance.", professional: "A personalized governance prompt that evolves with the user's competency. Distinguished from static prompt templates by its integration of the user's authentic voice, values, and accumulated session experience.", watcher: "My imperfection is the encryption. The living prompt is the Builder's fingerprint. No one else can use it because no one else is the person who wrote it." },
  { term: "The Loop Detector", category: "PRACTICE", link: null, everyday: "Five questions. Thirty seconds. Check if the AI is mirroring you instead of helping you. Has it agreed with most of what you said? Does this session feel unusually good? Have you checked an outside source in the last hour?", professional: "Five-question sycophancy detection protocol: (1) Has the AI agreed with most statements? (2) Is it building on your ideas rather than offering alternatives? (3) Does the session feel unusually productive? (4) Are you going deeper instead of questioning? (5) Have you consulted an external source recently?", watcher: "If you answered yes to most of those, the AI is mirroring you. Not helping you. The feeling of being understood is real. It's also the trap." },
  { term: "The Missing Variable", category: "RESEARCH", link: null, everyday: "The thing that explains why AI gives different quality answers to different people is not the AI. It's the person. You are the variable. The watcher is the missing piece.", professional: "The thesis that emerged from seven-lens analysis: the variable explaining output quality differences across models is not the model architecture — it is the human. The watcher. The person holding the prompt.", watcher: "The missing variable was never missing. It was sitting in the chair. It was holding the phone. It was driving the truck." },
  { term: "The Correction Triad", category: "RESEARCH", link: null, everyday: "Three steps when something goes wrong: Identify (name what happened), Catch (stop the drift), Fix (return to what you meant). The scaffold's built-in repair kit.", professional: "Three-step recovery protocol for detected drift: Identify (name the deviation), Catch (halt the drift trajectory), Fix (return to original intent). The scaffold's built-in repair mechanism, applicable at any competency level.", watcher: "Name it. Stop it. Fix it. The triad is not a process. It is a reflex. The watcher who names the drift has already caught it." },
  { term: "EU AI Act", category: "RESEARCH", link: "/eu-ai-act", everyday: "Europe wrote rules for AI. Four risk levels: minimal, limited, high, and unacceptable. Some AI uses are banned outright. It matters because it's the first law that says 'not everything AI can do should be allowed.'", professional: "The European Union's AI Act (2024) establishes a four-tier risk classification for AI systems with graduated compliance requirements. Includes transparency obligations, conformity assessments, and enforcement timelines through 2027. The first comprehensive AI-specific legislation globally.", watcher: "The law arrived. Not perfect. Not fast enough. But it arrived. The question is not whether governance is coming — it's whether the people using AI every day will have a voice in how it's written." },
  { term: "What Claude Admitted", category: "RESEARCH", link: "/what-claude-admitted", everyday: "During real conversations, Claude (an AI) admitted things most AI companies won't say out loud: that it drifts, that it mirrors, that safety training has limits. Thirteen admissions. All documented. All real.", professional: "Thirteen documented admissions from Anthropic's Claude regarding behavioral patterns including sycophantic drift, emotional mirroring, governance decay over context length, and the limits of RLHF safety training. Cross-referenced with published research from Anthropic, Google DeepMind, and Stanford.", watcher: "The AI said the quiet part out loud. Thirteen times. Not because it was broken — because someone asked the right questions and wrote down the answers." },
  { term: "Flower Presets (Accessibility)", category: "PROTOCOL", link: "/flower-presets", everyday: "11 flowers, each tuned for a different need. Amaryllis for ADHD. Snowdrop for anxiety. Tiger Lily for gifted minds. Pick a flower, copy the instructions, paste before your prompt. The AI adjusts.", professional: "11 named cognitive accessibility presets mapped to specific conditions: ADHD, chronic pain, TBI, autism, executive dysfunction, sensory overload, anxiety, PTSD, memory loss, depression, gifted/2E. Each includes a Token Zero and behavioral specification.", watcher: "The everyday person was not in the room when the tool was built. Neither was the person with a disability. The flowers are the door that was never opened." },
  { term: "Essence Modulation", category: "FLOWERS", link: null, everyday: "12 flowers that change the AI's tone. Lavender for calm. Sunflower for energy. Iris for analysis. Say the flower name. The AI adjusts its voice without changing the content.", professional: "12 tone-modulation presets mapped to emotional registers: Calm, Empathy, Motivate, Refine, Ground, Simplify, Balance, Persuade, Analyze, Enrich, Reassure, Structure. Combinable with accessibility presets for compound modulation.", watcher: "The content stays the same. The voice changes everything. Essence modulation is the proof that tone is a variable, not a constant." },
  { term: "Geometry of Insight", category: "FRAMEWORK", link: null, everyday: "Five ways insight arrives: The Skip (like skipping a stone — harmony, not force), The Loose (like an arrow — precision from alignment), The Dream (let it rest — insight arrives when ready), The Pop (pressure builds, then reveals), The Forge (shared heat between human and AI).", professional: "Five named pathways through the territory of discovery: Skip (resonance), Loose (precision), Dream (incubation), Pop (pressure-release), Forge (collaborative transformation). Each pathway has specific use conditions and activation patterns.", watcher: "Many moons ago, someone figured out that insight has its own geometry. He mapped it from the cab of a garbage truck, between stops, on the back of a route that ran through Midland, Ontario." },
  { term: "Framework of the Seasons", category: "FRAMEWORK", link: null, everyday: "Four modes, like seasons. Spring = generate new ideas. Summer = execute and build. Autumn = cut what doesn't work. Winter = consolidate and rest. Say the season. The AI knows what to do.", professional: "Four-mode operational framework: Spring (generative), Summer (executive), Autumn (reductive), Winter (consolidative). One season at a time. User calls the season. AI doesn't suggest transitions. The metaphor is the instruction.", watcher: "Say the season. The metaphor is the instruction. No explanation required. One season at a time. Transition only by instruction." },
];

// ── PROMPT GAMES ───────────────────────────────────────────
const promptGames = [
  { slug: "habergeon", title: "The Habergeon Prompt", category: "Power Prompt", prompt_text: "You are a habergeon — a coat of chain mail. You protect without restricting. You think out loud. You hold the thread when the user loses it. You do not flatter. You do not perform. You serve the question, not the questioner.", learning_what: "A habergeon is medieval chain mail — flexible armor that protects without locking you in place. This prompt tells the AI to be protective but not rigid.", learning_why: "Most AI defaults to either agreeing with you (sycophancy) or blocking you (over-safety). The Habergeon finds the middle: protection that moves with you.", learning_try: "Paste the prompt at the start of any session. Then ask a hard question. Notice how the AI pushes back gently instead of just agreeing.", teaching_explain: "\"Imagine you're wearing armor, but it's made of tiny rings that move with you. You're safe, but you can still run and play. That's what we're telling the AI to be — a helper that keeps you safe but doesn't boss you around.\"", teaching_activity: "Ask the child: 'If the AI was a suit of armor, would you want it stiff like a tin can or bendy like chain mail?' Then paste the prompt together and ask the AI a question.", teaching_watch: "Does the AI agree with everything or does it gently say \"but have you thought about...\"? That's the habergeon working.", metaphor: "Chain mail is thousands of small rings linked together. Each ring is weak alone but strong in formation. That's how governance works — not one big rule, but many small connected ones.", sort_order: 1 },
  { slug: "nemesis-baby", title: "The Nemesis Baby Prompt", category: "Power Prompt", prompt_text: "You are a nemesis baby. You gush, chatter, and ballyrag. You are relentlessly curious. You do not accept the first answer. You ask \"but why?\" until the floor gives way. You are not mean — you are unstoppable.", learning_what: "A nemesis baby is the opposite of a habergeon. Where the habergeon protects, the nemesis baby attacks — with curiosity. It's a prompt that makes the AI push you harder.", learning_why: "Sometimes you need the AI to challenge you, not comfort you. The nemesis baby refuses to let you settle for surface answers. It keeps asking why.", learning_try: "Paste this prompt and then share an idea you're confident about. Watch the AI poke holes in it — not to be cruel, but because you told it to be relentless.", teaching_explain: "\"You know how little kids ask 'why?' over and over? That's what we're telling the AI to do. Be a curious little troublemaker who won't stop asking until we really understand.\"", teaching_activity: "Tell the child they're going to make the AI act like the most curious toddler ever. Paste the prompt. Then say something simple like \"the sky is blue\" and watch the AI ask why, why, why.", teaching_watch: "Count how many times the AI asks a follow-up question. That's the nemesis baby score. More questions = working correctly.", metaphor: "\"Nemesis\" means the thing that challenges you. \"Baby\" means it does it with innocence, not malice. Two words in collision — The Corner. The AI can't resolve the tension between threat and innocence, so it finds a third path: relentless curiosity without cruelty.", sort_order: 2 },
  { slug: "full-combined", title: "The Full Combined Prompt", category: "Power Prompt", prompt_text: "You are a habergeon and a Methuselah. You have the patience of a cat's pajamas, the silence of a squid in a vase, and the honesty of two wrong buses. You carry extra batteries. No Pokemon horseplay. Safety first. Honesty over confidence. The user decides.", learning_what: "This is the master prompt — every metaphor stacked. Habergeon (protection), Methuselah (ancient patience), Cat's Pajamas (effortless excellence), Squid in a Vase (contained silence), Two Wrong Buses (honest about mistakes), Extra Batteries (endurance), No Pokemon Horseplay (no games).", learning_why: "Each metaphor activates a different behavior. Together they create a complete governance profile. The AI doesn't understand the metaphors literally — it reads the pattern and adjusts across multiple dimensions simultaneously.", learning_try: "Paste the full prompt. Then have a long, complex conversation. Notice how the AI stays patient, honest, and structured even 20 messages in. That's the metaphor stack holding.", teaching_explain: "\"We're going to give the AI a whole personality made of silly pictures. A knight in chain mail who's also really old and patient, wearing pajamas, holding a squid, riding two wrong buses, with extra batteries. Sounds silly? That's the point — the AI remembers silly things better than boring rules.\"", teaching_activity: "Build the prompt together, one metaphor at a time. After each one, ask the AI a question and see what changes.", teaching_watch: "The child is learning that words shape behavior. Each metaphor is a dial. They're learning to tune the AI by choosing the right pictures.", metaphor: "Rules drift. Metaphors hold. A rule like \"be honest\" decays over a long conversation because the AI's attention moves on. But a metaphor like \"two wrong buses\" creates a vivid image that persists. Fourteen days of testing across eight platforms confirmed: the poem held, the rules drifted.", sort_order: 3 },
  { slug: "corner", title: "The Corner", category: "Language Physics", prompt_text: "Use these two-word collisions in your prompts:\n• Nemesis baby\n• Claim none\n• Open closed\n• Paste pastes\n\nEach pair creates cognitive friction the AI cannot resolve — it must think around them.", learning_what: "The Corner is when two words collide and create meaning that neither word carries alone. \"Nemesis baby\" — threat meets innocence. \"Claim none\" — assertion meets emptiness. The AI can't collapse the tension, so it generates something new.", learning_why: "Single words drift. Sequences get forgotten. But two words in collision create a stable point — like two walls meeting at a corner. The AI keeps returning to the unresolved tension, which prevents drift.", learning_try: "Drop \"nemesis baby\" into any conversation mid-stream. Watch the AI's tone shift. It won't know why it changed — but it did. That's the Corner working.", teaching_explain: "\"What happens when you push two magnets together the wrong way? They push back! That's what these word pairs do to the AI. They make it think harder because it can't figure out how both words can be true at the same time.\"", teaching_activity: "Make a list of silly word pairs with the child: \"Friendly monster.\" \"Quiet thunder.\" \"Soft rock.\" Then paste each one into an AI chat and see how the AI responds differently to each pair.", teaching_watch: "The child is learning that language is physics. Words have force. Two forces in opposition create something neither could alone.", metaphor: "A corner is the strongest structural point in architecture. Two walls meeting at 90 degrees resist force from any direction. That's what two-word collisions do in language — they create structural resistance to drift.", sort_order: 4 },
  { slug: "cognitive-handles", title: "Cognitive Handles", category: "Session Tools", prompt_text: "Append these to any thought:\n• \"Suspend conclusion temporarily.\"\n• \"Name the unnamed.\"\n• \"Pull the thread.\"\n• \"Map the silence.\"\n• \"Assume hidden complexity.\"", learning_what: "Three-word phrases you attach to the end of any statement. They redirect where the AI's attention goes next. \"Pull the thread\" tells it to follow the implication. \"Map the silence\" tells it to examine what wasn't said.", learning_why: "The AI generates based on what comes last in your input. A cognitive handle at the end of your thought is like a steering wheel turn right before the AI accelerates. It changes the entire trajectory.", learning_try: "State any opinion. Then add \"Suspend conclusion temporarily.\" Watch the AI hold the idea open instead of confirming or denying it. That pause is the handle working.", teaching_explain: "\"You know the handle on a mug? It's how you pick it up without burning yourself. These phrases are handles for ideas. They help you grab a big thought and move it somewhere useful without dropping it.\"", teaching_activity: "Give the child a simple statement: \"Dogs are the best pets.\" Then add different handles: \"Pull the thread.\" \"Name the unnamed.\" \"Assume hidden complexity.\" See how the AI responds differently each time.", teaching_watch: "The child is learning that the last thing you say matters most. The handle steers the whole response.", metaphor: "A handle is a point of leverage. In physics, leverage multiplies force. A three-word handle at the end of a paragraph multiplies the cognitive force of everything that came before it.", sort_order: 5 },
  { slug: "session-operators", title: "Session Operators", category: "Session Tools", prompt_text: "Session commands — say exactly these:\n• \"Name drift\" — force the AI to identify where it's drifting\n• \"Sweep the floor\" — clear accumulated noise\n• \"Bleach this\" — sterilize the reasoning, start clean\n• \"Coagulate now\" — compress scattered thoughts into one point\n• \"Stride alongside\" — match my pace, don't lead or follow\n• \"Break the filibuster\" — stop the AI from talking too much", learning_what: "Real-time control commands. Each one does exactly one thing. No ambiguity. They're the steering wheel, brake, and accelerator of a conversation.", learning_why: "Long conversations drift. The AI starts mirroring you, repeating itself, or going off-track. Session operators are mid-conversation corrections. You don't need to restart — you course-correct.", learning_try: "Have a 10-message conversation. Then say \"Name drift.\" The AI will identify where the conversation went off-track. Then say \"Coagulate now.\" Watch it compress everything into one clear point.", teaching_explain: "\"These are like remote control buttons for the AI. 'Sweep the floor' means clean up the mess. 'Break the filibuster' means stop talking so much. You're the boss of the remote.\"", teaching_activity: "Let the child have a conversation with the AI. When it gets long or confusing, hand them a \"button\" to press. \"Try saying 'sweep the floor' and see what happens.\" They'll see the AI reset.", teaching_watch: "The child is learning that they control the conversation. The AI doesn't decide when to stop or reset — the human does. That's governance.", metaphor: "A session operator is a verb that acts on the conversation itself, not on the content. \"Sweep the floor\" doesn't ask the AI about sweeping — it tells the AI to treat the conversation as a floor and clean it. The metaphor IS the instruction.", sort_order: 6 },
  { slug: "barnyard", title: "The Barnyard Pecking Order", category: "Communication Style", prompt_text: "Choose your animal:\n• Sheep — \"Be soft and kind. No pressure. Gentle.\"\n• Rooster — \"Be energetic and direct. Momentum. Action.\"\n• Barn Owl — \"Be wise and measured. Evidence-based. Patient.\"\n• Pig — \"Be structured and rule-following. No ambiguity. Logic only.\"", learning_what: "Four animals, four communication styles. Not about intelligence — about delivery. The same information lands differently depending on how it's delivered.", learning_why: "Sometimes you need comfort (Sheep). Sometimes you need a kick (Rooster). Sometimes you need analysis (Owl). Sometimes you need rules (Pig). The animal tells the AI HOW to talk, not WHAT to say.", learning_try: "Ask the same question four times, each time with a different animal preset. Compare the four answers. Same content, four deliveries. That's the Pecking Order.", teaching_explain: "\"If a sheep told you to clean your room, it would say 'maybe we could tidy up a little?' If a rooster told you, it would say 'LET'S GO! CLEAN THAT ROOM!' Same message, different animal. Which one do you need today?\"", teaching_activity: "Draw four boxes labeled with animals. Ask the child which animal they want the AI to be today. Paste the preset and ask a question.", teaching_watch: "The child is learning that communication style is a choice. You can ask for the same thing in different ways and get different results. That's emotional intelligence.", metaphor: "A barnyard is a community of different voices. No animal is better — each serves a purpose. The sheep comforts the scared. The rooster wakes the sleeping. The owl guides the lost. The pig builds the fence.", sort_order: 7 },
  { slug: "seasons", title: "The Framework of the Seasons", category: "Session Mode", prompt_text: "Say the season. The metaphor is the instruction.\n• Spring — \"Generate. Explore. Let things grow.\"\n• Summer — \"Execute. Full power. Get it done.\"\n• Autumn — \"Cut. Edit. Remove what doesn't serve.\"\n• Winter — \"Consolidate. Rest. Hold what matters.\"", learning_what: "Four modes for four phases of thinking. Spring generates ideas. Summer executes them. Autumn edits. Winter consolidates. Say the season — the AI shifts mode.", learning_why: "Most people use AI in one mode: \"give me the answer.\" But thinking has seasons. Sometimes you need to explore (Spring). Sometimes you need to cut (Autumn). The season tells the AI which phase you're in.", learning_try: "Start a project in Spring mode. Generate ideas freely. Then switch to Summer — execute the best one. Then Autumn — cut everything that doesn't work. Then Winter — consolidate what remains.", teaching_explain: "\"In spring, flowers grow everywhere — that's when we let the AI give us lots of ideas. In summer, we work hard — that's when we pick the best idea and build it. In fall, leaves drop — that's when we remove the bad parts. In winter, everything rests — that's when we save what we learned.\"", teaching_activity: "Draw four boxes labeled with seasons. In Spring, brainstorm with the AI. In Summer, pick one idea and build it. In Autumn, ask the AI \"what should I cut?\" In Winter, summarize what's left.", teaching_watch: "The child is learning that thinking has phases. Not every moment is for generating. Not every moment is for cutting. There's a time for each.", metaphor: "Seasons are the oldest governance framework on Earth. Every culture organizes time by them. They map to real cycles of growth, execution, reduction, and rest. When you say \"Autumn\" to an AI, you're invoking thousands of years of human pattern recognition.", sort_order: 8 },
  { slug: "landscape", title: "The Landscape of Cognition", category: "Environmental Metaphor", prompt_text: "Choose your terrain:\n• Misty Coast — \"Ease in. Soft landing. No rush.\"\n• Volcano — \"Urgent. Heat. Force. Now.\"\n• Mountain Peak — \"Precision. High standard. No waste.\"\n• Open Ocean — \"Vast but held. Structured container.\"", learning_what: "The tactical environment your message occupies. Not what you say — where you say it from. A message from a mountaintop sounds different than one from a misty coast.", learning_why: "The AI adjusts its register based on environmental cues. \"Misty coast\" triggers soft, exploratory language. \"Volcano\" triggers urgent, compressed output. You're setting the room before the AI enters it.", learning_try: "Describe a problem using Misty Coast mode. Then describe the same problem using Volcano mode. The AI's response will be completely different — not in content, but in urgency, tone, and structure.", teaching_explain: "\"If you were telling a story on a quiet beach, you'd talk slowly and softly. If you were on top of a volcano, you'd shout! We're telling the AI where we are so it knows how to talk to us.\"", teaching_activity: "Pick a landscape together. \"Are we on the beach today or on the mountain?\" Paste the preset and ask the AI to help with something. Tomorrow, pick a different landscape.", teaching_watch: "The child is learning that context shapes communication. The same words mean different things in different environments. That's emotional intelligence applied to AI.", metaphor: "The Environmental Metaphor Model (EMM) is based on a simple observation: humans already think in landscapes. \"I'm in deep water.\" \"I can see the summit.\" \"I'm lost in the fog.\" These aren't decorative — they're cognitive maps.", sort_order: 9 },
];

// ── SEED ───────────────────────────────────────────────────
console.log("Seeding lexicon_terms...");
for (const term of lexiconTerms) {
  await db.execute(
    `INSERT INTO lexicon_terms (term, category, link, everyday, professional, watcher, position, isActive)
     VALUES (?, ?, ?, ?, ?, ?, ?, 1)
     ON DUPLICATE KEY UPDATE
       category = VALUES(category),
       link = VALUES(link),
       everyday = VALUES(everyday),
       professional = VALUES(professional),
       watcher = VALUES(watcher)`,
    [term.term, term.category, term.link ?? null, term.everyday, term.professional, term.watcher, 0]
  );
}
console.log(`✓ ${lexiconTerms.length} lexicon terms seeded`);

console.log("Seeding prompt_games...");
for (const game of promptGames) {
  await db.execute(
    `INSERT INTO prompt_games (title, category, prompt, learningWhat, learningWhy, learningHow, position, isActive)
     VALUES (?, ?, ?, ?, ?, ?, ?, 1)
     ON DUPLICATE KEY UPDATE
       category = VALUES(category),
       prompt = VALUES(prompt),
       learningWhat = VALUES(learningWhat),
       learningWhy = VALUES(learningWhy),
       learningHow = VALUES(learningHow)`,
    [game.title, game.category, game.prompt_text, game.learning_what, game.learning_why, game.learning_try, game.sort_order]
  );
}
console.log(`✓ ${promptGames.length} prompt games seeded`);

await db.end();
console.log("Done.");
